# Local configuration file
logging:
  pattern.console: >-
    %white(%d{mmss})
    %clr(${LOG_LEVEL_PATTERN:%replace(%replace(%replace(%replace(%p){
    'ERROR','E'}){'WARN', 'W'}){'DEBUG', 'D'}){'INFO', 'I'}})
    %m
    %blue(%logger{0})
    %n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
  level:
    org.spring: INFO
#    org.springframework.security: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring.datasource.password: 11235

management.security.enabled: false
security:
  basic.enabled: false
#  security.user:
#    name: admin
#    password: admin