
logging:
  pattern.console: >-
    %white(%d{mmss})
    %clr(${LOG_LEVEL_PATTERN:%replace(%replace(%replace(%replace(%p){
    'ERROR','E'}){'WARN', 'W'}){'DEBUG', 'D'}){'INFO', 'I'}})
    %m
    %blue(%logger{0})
    %n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
  level:
    org.fakebook: DEBUG
server:
  port: 8080

auth:
  users:
    - name: usr1
      pass: psw
      roles: USER
    - name: usr2
      pass: psw
      roles: USER, ADMIN
  clients:
    - id: m1
      secret: mm
      scopes: default
      grant-types: password, refresh_token, implicit, authorization_code, client_credentials
      auto-approve: true
      redirect-uris: localhost:8080
    - id: m2
      secret: mm
      scopes: default
      grant-types: password
      auto-approve: true
    - id: m3
      secret: mm
      scopes: default
      grant-types: authorization_code
      redirect-uris: localhost:8080
      auto-approve: true
    - id: m4
      secret: mm
      scopes: default
      grant-types: client_credentials
      auto-approve: true
