
server:
  contextPath: /
  port: 8081

logging:
  pattern.console: >-
    %white(%d{mmss})
    %clr(${LOG_LEVEL_PATTERN:%replace(%replace(%replace(%replace(%p){
    'ERROR','E'}){'WARN', 'W'}){'DEBUG', 'D'}){'INFO', 'I'}})
    %m
    %blue(%logger{0})
    %n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
  level:
    org.spring: INFO

spring:
  profiles.active: local
  application.name: resource-service-extended

security:
  oauth2:
    resource:
#      filter-order: 3
      userInfoUri: http://localhost:8080/me
#    client:
#      client-id: apis
#      client-secret: apissec
